# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bc20cff40f48082f5a56dc65494f033e10231c893a0b8ed254d6f7023e5be728ea9fa94be8c30d0d6822d59b5deb84de8f74c4662accf9e3cfdda9b537f0f06

test:
  secret_key_base: 9663212ec798b1f121fed663099cb7a236f02eb0ffda31b791e3e3e9803a1e03c3e3e920a5db960873d5b1443ac369b0b8987279a4dc5a97e5e95875292ac57d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
